---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: what-the-helm
  namespace: default
spec:
  releaseName: what-the-helm
  chart:
    git: ssh://sriram1103@github1.com/what-the-helm
    ref: master
    path: deploy.yaml
