---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: what-the-helm
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: what-the-helm
  chart:
    git: ssh://sriram1103@github1.com/what-the-helm
    ref: master
    path: deploy.yaml
